version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: The Empire's App
    path: ""
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
