version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: empty
    path: ""
    text-resources:
      - path: src/langs/*.json
        format: flat-key-value
       - path: "*.tsx"
        format: react-hardcoded
